spring:
  application:
    name: TelegramPrinterBot

telegrambots:
  enabled: true
  bots:
    username: HomePrinterBot
    token: "8438331015:AAF6eWXQU3htN4Kr4ybYjCjUcgzpS-b0BY4"
    support_chat_id: "-4986887147"
  print_script_path: /app/print.sh
